// generated by stringer -type=SieveAlgo; DO NOT EDIT

package primes

import "fmt"

const _SieveAlgo_name = "EratosthenesAlgo"

var _SieveAlgo_index = [...]uint8{0, 16}

func (i SieveAlgo) String() string {
	if i < 0 || i+1 >= SieveAlgo(len(_SieveAlgo_index)) {
		return fmt.Sprintf("SieveAlgo(%d)", i)
	}
	return _SieveAlgo_name[_SieveAlgo_index[i]:_SieveAlgo_index[i+1]]
}
